name: acts
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4
  - torch=1.8.1
  - pip:
    - pytorch-lightning==1.2.5
    - torchtext==0.9.0
    - seaborn==0.11.0
    - tensorboard==2.3.0
    - tabulate==0.8.7
    - tqdm==4.50.2
    - pillow==8.0.1
    - numpy==1.19.2
    - spacy==3.0.5
    - datasets==1.5.0
