#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=InferSentv1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=12:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2019
module load Python/3.7.5-foss-2019b
module load Anaconda3/2018.12

# Your job starts in the directory where you call sbatch
cd $HOME/Practical1
# Activate your environment
source activate acts_environment_lisa
# Run your code
srun python -u InferSent_train.py